
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label1;
	private global::Gtk.Entry codigo;
	private global::Gtk.Entry nombre;
	private global::Gtk.Label label3;
	private global::Gtk.RadioButton radiodf;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.RadioButton radiobutton4;
	private global::Gtk.Label label4;
	private global::Gtk.CheckButton checkreino;
	private global::Gtk.CheckButton checkportugal;
	private global::Gtk.CheckButton checkmexico;
	private global::Gtk.CheckButton checkmace;
	private global::Gtk.CheckButton checkaustralia;
	private global::Gtk.Label label5;
	private global::Gtk.SpinButton estados;
	private global::Gtk.Label label6;
	private global::Gtk.Calendar calendario;
	private global::Gtk.Button terminar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 10;
		w1.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w2.X = 10;
		w2.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.codigo = new global::Gtk.Entry ();
		this.codigo.WidthRequest = 332;
		this.codigo.CanFocus = true;
		this.codigo.Name = "codigo";
		this.codigo.IsEditable = true;
		this.codigo.InvisibleChar = '●';
		this.fixed1.Add (this.codigo);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.codigo]));
		w3.X = 65;
		w3.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nombre = new global::Gtk.Entry ();
		this.nombre.WidthRequest = 329;
		this.nombre.CanFocus = true;
		this.nombre.Name = "nombre";
		this.nombre.IsEditable = true;
		this.nombre.InvisibleChar = '●';
		this.fixed1.Add (this.nombre);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.nombre]));
		w4.X = 66;
		w4.Y = 38;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("1) Capital de Mexico");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w5.X = 8;
		w5.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiodf = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("DF"));
		this.radiodf.CanFocus = true;
		this.radiodf.Name = "radiodf";
		this.radiodf.DrawIndicator = true;
		this.radiodf.UseUnderline = true;
		this.radiodf.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radiodf);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiodf]));
		w6.X = 5;
		w6.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Monterrey"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radiodf.Group;
		this.fixed1.Add (this.radiobutton3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton3]));
		w7.X = 5;
		w7.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Guadalajara"));
		this.radiobutton4.CanFocus = true;
		this.radiobutton4.Name = "radiobutton4";
		this.radiobutton4.DrawIndicator = true;
		this.radiobutton4.UseUnderline = true;
		this.radiobutton4.Group = this.radiodf.Group;
		this.fixed1.Add (this.radiobutton4);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton4]));
		w8.X = 5;
		w8.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("2) Paises de Europa");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w9.X = 8;
		w9.Y = 195;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkreino = new global::Gtk.CheckButton ();
		this.checkreino.CanFocus = true;
		this.checkreino.Name = "checkreino";
		this.checkreino.Label = global::Mono.Unix.Catalog.GetString ("Reino Unido");
		this.checkreino.DrawIndicator = true;
		this.checkreino.UseUnderline = true;
		this.fixed1.Add (this.checkreino);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkreino]));
		w10.X = 5;
		w10.Y = 258;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkportugal = new global::Gtk.CheckButton ();
		this.checkportugal.CanFocus = true;
		this.checkportugal.Name = "checkportugal";
		this.checkportugal.Label = global::Mono.Unix.Catalog.GetString ("Portugal");
		this.checkportugal.DrawIndicator = true;
		this.checkportugal.UseUnderline = true;
		this.fixed1.Add (this.checkportugal);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkportugal]));
		w11.X = 5;
		w11.Y = 218;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkmexico = new global::Gtk.CheckButton ();
		this.checkmexico.CanFocus = true;
		this.checkmexico.Name = "checkmexico";
		this.checkmexico.Label = global::Mono.Unix.Catalog.GetString ("Mexico");
		this.checkmexico.DrawIndicator = true;
		this.checkmexico.UseUnderline = true;
		this.fixed1.Add (this.checkmexico);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkmexico]));
		w12.X = 5;
		w12.Y = 238;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkmace = new global::Gtk.CheckButton ();
		this.checkmace.CanFocus = true;
		this.checkmace.Name = "checkmace";
		this.checkmace.Label = global::Mono.Unix.Catalog.GetString ("Macedonia");
		this.checkmace.DrawIndicator = true;
		this.checkmace.UseUnderline = true;
		this.fixed1.Add (this.checkmace);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkmace]));
		w13.X = 5;
		w13.Y = 278;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkaustralia = new global::Gtk.CheckButton ();
		this.checkaustralia.CanFocus = true;
		this.checkaustralia.Name = "checkaustralia";
		this.checkaustralia.Label = global::Mono.Unix.Catalog.GetString ("Australia");
		this.checkaustralia.DrawIndicator = true;
		this.checkaustralia.UseUnderline = true;
		this.fixed1.Add (this.checkaustralia);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkaustralia]));
		w14.X = 5;
		w14.Y = 298;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("3) Cuantos estados Tiene Mexico");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w15.X = 8;
		w15.Y = 332;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.estados = new global::Gtk.SpinButton (0, 100, 1);
		this.estados.CanFocus = true;
		this.estados.Name = "estados";
		this.estados.Adjustment.PageIncrement = 10;
		this.estados.ClimbRate = 1;
		this.estados.Numeric = true;
		this.fixed1.Add (this.estados);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.estados]));
		w16.X = 5;
		w16.Y = 362;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("4) Dia en que termino la segunda guuerra Mundial");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w17.X = 242;
		w17.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendario = new global::Gtk.Calendar ();
		this.calendario.CanFocus = true;
		this.calendario.Name = "calendario";
		this.calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendario);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendario]));
		w18.X = 283;
		w18.Y = 120;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terminar = new global::Gtk.Button ();
		this.terminar.WidthRequest = 100;
		this.terminar.HeightRequest = 35;
		this.terminar.CanFocus = true;
		this.terminar.Name = "terminar";
		this.terminar.UseUnderline = true;
		this.terminar.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.terminar);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.terminar]));
		w19.X = 464;
		w19.Y = 360;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 606;
		this.DefaultHeight = 421;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.terminar.Clicked += new global::System.EventHandler (this.OnTerminarClicked);
	}
}
